default: &default
  adapter: postgresql 
  pool: 5
  host: localhost
  username: peady
  password: <%= ENV['DATABASE_PASSWORD'] %>
  timeout: 5000

development:
  <<: *default
  database: productify_development 

test:
  <<: *default
  database: productify_test 

production:
  <<: *default
  database: productify_production
